# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TaiwanpetadoptionApp-ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TaiwanpetadoptionApp-ios

  target 'TaiwanpetadoptionApp-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TaiwanpetadoptionApp-iosUITests' do
    # Pods for testing
  end
pod 'Alamofire', '~> 5.4'
pod 'Firebase/Analytics'
pod 'Google-Mobile-Ads-SDK'
pod 'JGProgressHUD'
pod 'Firebase/Auth'
pod 'Firebase/Crashlytics'
pod 'JJFloatingActionButton'
pod 'Firebase/Database'
pod 'Toaster'
pod 'Firebase/Storage'
pod 'Firebase/Analytics' 
pod 'JXBanner'

pod 'RxSwift', '~> 5'
pod 'RxCocoa', '~> 5'
pod 'RxBlocking', '~> 5'
pod 'CLImagePickerTool'
        pod 'FBSDKLoginKit'
    pod 'GoogleSignIn'
    pod 'Firebase/Auth'
end
